### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by miguelnieves2** [vpalcar/calendar_appbar#5] opened 2021-07-31 19:46 UTC
Hello, I would like to know if it is possible to change to Spanish language?
I really liked this package and it would be very useful to have it in Spanish.

**Comment by vpalcar** [comment] 2021-08-02 10:31
Hi, the internationalization of the plugin is now on the top of my priority list for this plugin.

**Comment by sud0su** [comment] 2021-08-21 09:53
> Hello, I would like to know if it is possible to change to Spanish language?
> I really liked this package and it would be very useful to have it in Spanish.

I have created the pull request to this thing, hopefully the pull request can be merge asap, and then updating the package in pub.dev.

This is a nice package, i love it.. 😁

**Comment by vpalcar** [comment] 2021-08-22 18:47
I went through your suggested changes and the part with the local support is made very good. I only have a problem with the selection of short or long forms of weekdays. The problem is with the long forms as they don’t fit into the scrolling container (I'll add the picture). If you like me to I can remove that long and short weekdays functionality or you can fix the described issue. The package won’t be updated on pub.dev until those problems aren’t fixed.

**Comment by vpalcar** [comment] 2021-08-22 18:50
![Simulator Screen Shot - iPhone 12 Pro - 2021-08-22 at 20 50 18](https://user-images.githubusercontent.com/76632000/130366602-dc452a1e-7d9f-4f46-9aab-b965e0350edc.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-08-22 at 20 50 18](https://user-images.githubusercontent.com/76632000/130366605-525c91b7-f7f9-4368-b5fc-d4eb4ebfb1b3.png)

**Comment by sud0su** [comment] 2021-08-23 04:38
what emulator do you use to debug? i tried on iPhone 12 pro max emulators and Pixel emulator and everything is good.

<img width="803" alt="Screen Shot 2021-08-23 at 11 33 48" src="https://user-images.githubusercontent.com/6576959/130390662-0ca47a31-a6c5-45b1-a03d-327fad068d2a.png">

**Comment by vpalcar** [comment] 2021-08-23 23:22
Both of the mentioned emulators are the biggest representation of each side, Android and iOS. Try with iPhone 12 or iPhone SE.

**Comment by vpalcar** [comment] 2021-08-24 20:19
Hi, I merged the pull request and deleted the functionality of short and long form of a weekday so at least internationalization can be published to pub.dev. Thank you for your help and feel free to improve that issue with forms of text and we can implement it in the near future

**Closed by vpalcar** 2021-08-24 20:19 UTC
